default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: recipe_dev_db
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: recipe_test_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: recipe_prod_db
  pool: 5
  timeout: 5000